export const types = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
    CLEAR_CART: 'CLEAR_CART',
    SET_USER: 'SET_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_PRODUCT_DETAILS: 'SET_PRODUCT_DETAILS',
    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR'
};